I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/starting.rpy", line 18, in script
    with pause(2)
  File "game/starting.rpy", line 18, in <module>
    with pause(2)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/starting.rpy", line 18, in script
    with pause(2)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/starting.rpy", line 18, in <module>
    with pause(2)
NameError: name 'pause' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Wed Nov 13 23:27:38 2024
