I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\USER\Desktop\renpy things\.vscode\game name here\game/Hide&Seek/filedownload_ren.py.
Exception: In 'C:\\Users\\USER\\Desktop\\renpy things\\.vscode\\game name here\\game/Hide&Seek/filedownload_ren.py', there are no """renpy blocks, so every line is ignored.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\main.py", line 470, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\script.py", line 929, in load_appropriate_file
    data, stmts = self.load_file(dir, fn + source)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\script.py", line 721, in load_file
    stmts = renpy.parser.parse(fullfn)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\parser.py", line 1676, in parse
    lines = list_logical_lines(fn, filedata, linenumber)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\lexer.py", line 301, in list_logical_lines
    data = ren_py_to_rpy(data, filename)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\lexer.py", line 1659, in ren_py_to_rpy
    raise Exception('In {!r}, there are no """renpy blocks, so every line is ignored.'.format(filename))
Exception: In 'C:\\Users\\USER\\Desktop\\renpy things\\.vscode\\game name here\\game/Hide&Seek/filedownload_ren.py', there are no """renpy blocks, so every line is ignored.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
 
Tue Dec 10 00:12:55 2024
