I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/RPG_fight_scrypt/WWD3.rpy", line 105, in script
    scene black with Fade(1,1)
TypeError: Fade() missing 1 required positional argument: 'in_time'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/RPG_fight_scrypt/WWD3.rpy", line 105, in script
    scene black with Fade(1,1)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 1361, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/exports/statementexports.py", line 257, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/display/core.py", line 1578, in do_with
    return self.interact(trans_pause=True,
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/display/core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/display/core.py", line 2666, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/display/core.py", line 2575, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: Fade() missing 1 required positional argument: 'in_time'

macOS-12.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
not_yet_setted 1.0
Wed Dec 11 09:55:04 2024
