I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 528, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
TypeError: cannot pickle '_io.TextIOWrapper' object (perhaps store.file = <_io.TextIOWrapper name='C:\\Users\\USER\\Desktop\\GiftForYou;)\\hint.txt' mode='w' encoding='UTF-8'>)
=======
  File "game/act2.rpy", line 432, in script
    jump act3
ScriptError: could not find label 'act3'.
>>>>>>> a1e694a6cd761e1c08e81a080a66d67f685ca289

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 528, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\loadsave.py", line 436, in save
    reraise(t, e, tb)
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\loadsave.py", line 417, in save
    dump((roots, renpy.game.log), logf)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\compat\pickle.py", line 107, in dump
    pickle.dump(o, f, pickle.HIGHEST_PROTOCOL if highest else PROTOCOL)
TypeError: cannot pickle '_io.TextIOWrapper' object (perhaps store.file = <_io.TextIOWrapper name='C:\\Users\\USER\\Desktop\\GiftForYou;)\\hint.txt' mode='w' encoding='UTF-8'>)
=======
  File "game/act2.rpy", line 432, in script
    jump act3
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'act3'.
>>>>>>> a1e694a6cd761e1c08e81a080a66d67f685ca289

macOS-12.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
Doki Doki
Fixed     1.0
<<<<<<< HEAD
Thu Dec 19 00:12:49 2024
=======
Tue Dec 17 18:31:42 2024
>>>>>>> a1e694a6cd761e1c08e81a080a66d67f685ca289
