I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/RPG_fight_scrypt/WWD3.rpy", line 43, in script
    scene outside with Fade(O.5,1.0,1.5)
SyntaxError: invalid syntax (WWD3.rpy, line 43)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/RPG_fight_scrypt/WWD3.rpy", line 43, in script
    scene outside with Fade(O.5,1.0,1.5)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/python.py", line 1207, in py_eval
    code = py_compile(code, 'eval')
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/python.py", line 1144, in py_compile
    raise e
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/python.py", line 1081, in py_compile
    raise orig_e
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/python.py", line 1073, in py_compile
    tree = compile(source, filename, py_mode, ast.PyCF_ONLY_AST | flags, 1)
SyntaxError: invalid syntax (WWD3.rpy, line 43)

macOS-12.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
not_yet_setted 1.0
Tue Dec 10 12:12:07 2024
